name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build all apps
        run: npx turbo run build

      - name: Run backend tests
        run: npm run test --workspace=apps/backend

      # Check if Dockerfile exists
      - name: Debug folder structure
        run: |
          echo "Checking backend directory contents:"
          ls -la
          echo "---"
          ls -la apps
          echo "---"
          ls -la apps/backend
          echo "---"
          cat apps/backend/Dockerfile || echo "Dockerfile NOT FOUND"

    
      - name: Dockerize Backend
        run: docker build -t backend -f apps/backend/Dockerfile .

      - name: Dockerize Frontend
        run: docker build -t frontend ./apps/frontend
