
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build all apps
        run: npx turbo run build

      - name: Run backend tests
        run: npm run test --workspace=apps/backend

      # ===== Docker Build Steps (Fixed) =====
      - name: Build Backend Docker Image
        working-directory: apps/backend  # Critical change
        run: |
          # Only build if Dockerfile exists
          if [ -f Dockerfile ]; then
            docker build -t backend .
          else
            echo "No Dockerfile found in apps/backend, skipping Docker build"
          fi

      - name: Build Frontend Docker Image
        working-directory: apps/frontend  # Critical change
        run: |
          if [ -f Dockerfile ]; then
            docker build -t frontend .
          else
            echo "No Dockerfile found in apps/frontend, skipping Docker build"
          fi